version: '3'
services:
  mongodb:
    image: mongo:3.0.14
    container_name: jshort_db
    ports:
      - 27017:27017

  jshort:
    build: .
    container_name: jshort
    command: ["npm", "run", "devdockerstart"]
    environment:
      - HOSTNAME=localhost
      - PORT=3000
      - MONGO_URL=mongodb
    ports:
      - 3000:3000
    links:
      - mongodb
    volumes:
      - ./:/jshort
